### ISSUE TITLE
How to generate attention heatmap about "docs/attention_temporal.png"?

### ISSUE THREAD

**Issue by AllenMao** [muzairkhattak/ViFi-CLIP#1]

**Comment by hanoonaR** [comment]
Hi @AllenMao ,

Thank you for showing interest in our work. We compute the attention maps using relevancy maps obtained from various attention layers of the CLIP model following this [paper](https://openaccess.thecvf.com/content/ICCV2021/papers/Chefer_Generic_Attention-Model_Explainability_for_Interpreting_Bi-Modal_and_Encoder-Decoder_Transformers_ICCV_2021_paper.pdf). You can refer to their repository or this [notebook](https://github.com/hila-chefer/Transformer-MM-Explainability/blob/main/CLIP_explainability.ipynb) for further implementation details. We replace the MHSA blocks in the residual blocks of our ViFiCLIP model [here](https://github.com/muzairkhattak/ViFi-CLIP/blob/b853c5642c37e62c1376ea1abdcb4386f8df7a08/clip/model.py#L172) with a locally defined MHSA function to use forward hooks in its attention layers.

Hope this helps, Thank you.

**Comment by AllenMao** [comment]
> r repositor

Thank you for your reply!
