### ISSUE TITLE
t-SNE visualization code

### ISSUE THREAD

**Issue by minghu0830** [muzairkhattak/ViFi-CLIP#12]
Hello, thank you for your amazing work. I am integrating your work into my CVPR2024 work, could you possibly share the code for the t-SNE visualization? Thank you very much.

**Comment by muzairkhattak** [comment]
Hi @minghu0830,

Thank you for showing interest in our work and sorry for the delayed response.

We were trying to search for the notebook that we used and found a version of it. It has been uploaded [at this link. ](https://drive.google.com/file/d/15qVRmSzikyEGhPdN6MpYp6NZ3-nNlQwG/view?usp=sharing).

I hope that could be of some help. 

Kind regards,
Muhammad Uzair

**Comment by wangwen39** [comment]
@muzairkhattak 
Thank so much for sharing the codes of this amazing work. 
Can you share the code for attention map visualization of Figure 4 or 5?

**Comment by muzairkhattak** [comment]
Hi @wangwen39 @minghu0830,

Sorry for the delayed response. Unfortunately we don't have a exact code for that at the moment. 

We adapted code [from this repository](https://github.com/hila-chefer/Transformer-MM-Explainability/blob/main/CLIP_explainability.ipynb) for generating attention maps for ViFi-CLIP.

Specifically, you will need to replace the pytorch official `nn.MultiheadAttention` in CLIP repo with `MultiheadAttention` given by this repo in `auxilary.py` [at this line](https://github.com/hila-chefer/Transformer-MM-Explainability/blob/58eaea85ac9c34aff052f368514b35d2e4c8dd3c/CLIP/clip/auxilary.py#L265C7-L265C25).

I hope that could be helpful! 

Thank you.
