### ISSUE TITLE
 Inquiry about Finetuning CLIP Model on Kinetics Dataset Duration

### ISSUE THREAD

**Issue by SHIBOYA** [muzairkhattak/ViFi-CLIP#14]
I have been closely following your work and am particularly interested in the methodologies you've employed in your recent research.

I am writing to inquire about some specifics regarding the finetuning process of the CLIP model on the Kinetics dataset, which I noticed was a part of your study. Specifically, I am keen to understand the approximate duration required for this fine-tuning process.

Additionally, any tips or recommendations you might have based on your experience with this process would be greatly appreciated.

Thank you very much for your time and assistance. I look forward to your response and any insights you can provide.

Best regards!

**Comment by muzairkhattak** [comment]
Hi @SHIBOYA,

Thank you for showing interest in ViFi-CLIP! 

For training ViFi-CLIP B/16 on the K400 dataset, it takes around 22 hours using 8 A100 GPUs. 

Thank you!
