### ISSUE TITLE
关于模型参数量问题

### ISSUE THREAD

**Issue by xiezexun** [muzairkhattak/ViFi-CLIP#15]
作者您好，我想咨询一下您的ViFi-CLIP-L/14模型参数量有多少

**Comment by muzairkhattak** [comment]
Hi @xiezexun,

Thank you for showing interest in ViFi-CLIP!

ViFi-CLIP does not use any additional parametric component in its framework, thus it has same parameters as of vanilla CLIP model. For ViFi-CLIP ViT-L/14, it has around 427.62 M parameters (same as of CLIP ViT-L/14).

Thank you!
