### ISSUE TITLE
Questions about model complexity calculation

### ISSUE THREAD

**Issue by byminji** [muzairkhattak/ViFi-CLIP#18]
Hi, I am trying to reproduce the model complexity calculation including GLOPs, params and throughput (TP).
Could you please share the library or code snippets used for the paper?
Also, I am curious if the FLOPs and TP are measured for both vision and text encoders.

Thanks in advance :)

**Comment by muzairkhattak** [comment]
Hi @byminji,

Thank you for showing interest in ViFi-CLIP! 

Regarding your queries, kindly note the following:
1) For calculating GFLOPs, we used the FlopCountAnalysis function from fvcore library. You can use the reference code [as detailed here. ](https://github.com/facebookresearch/fvcore/blob/main/docs/flop_count.md)
2) For throughput, we modified the forward function of the ViFi-CLIP and used the following function:
```@torch.no_grad()
def throughput(data_loader, model, logger, text_labels):
    model.eval()
    texts = text_labels.cuda(non_blocking=True)
    if texts.shape[0] == 1:
        texts = texts.view(1, -1)

    for idx, batch_data in enumerate(data_loader):
        images = batch_data["imgs"].cuda(non_blocking=True)
        images = images.view((-1, config.DATA.NUM_FRAMES, 3) + images.size()[-2:])
        batch_size = images.shape[0]
        for i in range(50):
            model(images, texts)
        torch.cuda.synchronize()
        logger.info(f"throughput averaged with 30 times")
        tic1 = time.time()
        for i in range(30):
            model(images, texts)
        torch.cuda.synchronize()
        tic2 = time.time()
        logger.info(f"batch_size {batch_size} throughput {30 * batch_size / (tic2 - tic1)}")
        logger.info("Exiting from the main code --------------")
        exit()
```
 
3) The FLOPs and throughput are calculated using a single video-text pair, and both encoders are used for calculation. You can also refer to XCLIP issue [at this link. ](https://github.com/microsoft/VideoX/issues/66)

I hope that helps! 

Thank you and kind regards!

**Comment by byminji** [comment]
Thanks for your kind regards :)

I have a follow-up question. Did you use FP32 of FP16 for measurement?

Thank you so much 👍

**Comment by muzairkhattak** [comment]
We use `model.float()` operation to initialize the model (as shown [at this line](https://github.com/muzairkhattak/ViFi-CLIP/blob/e2d1948307f582052078eb8a4afbeb50247166f1/trainers/vificlip.py#L247)). This means that the calculation is being done in FP32.

**Comment by muzairkhattak** [comment]
Hi @byminji,
 
Closing this issue, feel free to open it incase there are any questions.

Thank you!
