### ISSUE TITLE
Question about ssv2 data augmentations

### ISSUE THREAD

**Issue by tomchen-ctj** [muzairkhattak/ViFi-CLIP#2]
Hi, thank you for your solid work and code releases!

I'm a bit confused about augmentations for ssv2 dataset. It seems for all the datasets, a default augmentation is employed. But for ssv2, the random flip should not be applied as it will harm the semantic of some categories, e.g. 'Pulling something from left to right', 'Pulling something from right to left'.

By fixing this, you might get a higher performance in ssv2 I guess.

**Comment by muzairkhattak** [comment]
Hi @tomchen-ctj,

Thank you for showing interest in our work!

Yes, we use same set of augmentations for all datasets and methods. Additionally, as you mentioned, turning off random flipping will indeed improve results for SSv2. 

In this work, we focused on highlighting the significance of a simple competitive baseline for videos with respect to architecture, and tried to keep almost all hyper-parameters constant across datasets. Improving the training strategies, dataset specific augmentations and other hyper-parameters would further enhance the performance. 

Kind regards
Uzair
