### ISSUE TITLE
Inference code

### ISSUE THREAD

**Issue by LilyTheBear** [muzairkhattak/ViFi-CLIP#4]
Would you mind to add a sample inference code ?

I wrote one it had way to many issues with half vs float tensors. I took care of it but then it had many other issues. All fixed but now the tensor sizes dont match. 

Running the eval code based on main.py and the command line you suggested results into many issues with apax. Is there an easy way to just run it on a sample video with 16 frames and a text sentence?

**Comment by tomer196** [comment]
Anyone can help with this kind of script?

**Comment by muzairkhattak** [comment]
Hi, sorry for the delayed reply. 

We will share a sample script / jupyter notebook in upcoming days.

Thank you!

**Comment by muzairkhattak** [comment]
Hi @LilyTheBear, @tomer196, @odh1995, @dahlian00 and @ooza,

We have released a Jupyter Notebook containing simple code to perform ViFi-CLIP inference on custom video. You can directly find it [at this link.](https://github.com/muzairkhattak/ViFi-CLIP/blob/main/ViFi-CLIP_Inference_custom_video.ipynb).

The good news is that it does not require any installation of Apex libaray.

Let me know in case there are any further queries! 

Thank you and kind regards!
