### ISSUE TITLE
[Question] Hardware configuration 

### ISSUE THREAD

**Issue by karelin** [muzairkhattak/ViFi-CLIP#5]
What was the hardware configuration for the fine-tuning and what time did it take?

**Comment by muzairkhattak** [comment]
Hi @karelin,

Thank you for showing interest in ViFi-CLIP!

To fine-tune ViFi-CLIP- B/16 model on K400, we used a single DGX machine with 8 A100 GPUs and it takes roughly 1 day to train for 30 epochs with this hardware. 

Please let us know incase you have any further questions. 

Thank you and kind regards!
