### ISSUE TITLE
Question about the results

### ISSUE THREAD

**Issue by Adeelyousaf** [muzairkhattak/ViFi-CLIP#6]
Hi,

Thanks for sharing a well-written code.
Kindly, can you clarify one thing: the ZS results for the Vanilla CLIP on UCF101 are calculated using "a photo of a {class}" or using 48 templates provided in the original CLIP paper.

Kind Regards

**Comment by muzairkhattak** [comment]
Hi @Adeelyousaf,

Thank you for showing interest in ViFi-CLIP!

For evaluating ZS results, we do not use any prompt template. We directly utilize "{class}" as the prompt. In our experiments, we have noted that using any prompt for zero-shot evaluation results in less performance as compared to using no prompt at all.

I hope that clarifies your query, please let us know in case you have any further question!

Thank you and kind regards!
