### ISSUE TITLE
LICENSE not Defined

### ISSUE THREAD

**Issue by rachmadionl** [muzairkhattak/ViFi-CLIP#7]
Hi,

Thank you for an interesting work demonstrating the full extent of CLIP!
May I know what is the license of the code and the models for this work? Providing license would be helpful.

Thanks.

**Comment by muzairkhattak** [comment]
Hi @rachmadionl,

We have added a MIT license for this code repository and associated models. 

You can [check it here.](https://github.com/muzairkhattak/ViFi-CLIP/blob/main/LICENSE)

Thank you and kind regards!

**Comment by muzairkhattak** [comment]
Feel free to reopen the issue if there are any questions.

Thank you!
