### ISSUE TITLE
Issue downloading pre-trained weights

### ISSUE THREAD

**Issue by ee2110** [muzairkhattak/ViFi-CLIP#8]
Hi, thank you again for the great work! I tried to download the pre-trained weights from [here ](https://github.com/muzairkhattak/ViFi-CLIP#zero-shot-results) by click on the given link, but we unable to access it, not sure if it is restricted, it has no respond even we clicked the download button or using wget.

https://mbzuaiac-my.sharepoint.com/personal/uzair_khattak_mbzuai_ac_ae/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fuzair%5Fkhattak%5Fmbzuai%5Fac%5Fae%2FDocuments%2Fvifi%5Fclip%5Fweights%2Fzero%5Fshot%5Fweights%2Fvifi%5Fclip%5F10%5Fepochs%5Fk400%5Ffull%5Ffinetuned%2Epth&parent=%2Fpersonal%2Fuzair%5Fkhattak%5Fmbzuai%5Fac%5Fae%2FDocuments%2Fvifi%5Fclip%5Fweights%2Fzero%5Fshot%5Fweights&ga=1

Could you help to advice how we can get the pre-trained weights? Thank you.

**Comment by muzairkhattak** [comment]
Hi, Thank you for showing interest in ViFi-CLIP!

Can you check the link again? I have reset the permission settings again!

You can also check this link here to [download the weights.](https://mbzuaiac-my.sharepoint.com/:f:/g/personal/uzair_khattak_mbzuai_ac_ae/EopGOfZcerVIm9ehigcNec4BznvoCvxgY1-LyeX4JAOw-w)

Thank you.

**Comment by ee2110** [comment]
Thank you so much for your prompt response! It works and I can download it now, I also doubt the restriction might come from my network. Thank you so much for your time!

**Comment by ee2110** [comment]
Thank you so much for your prompt response! It works and I can download it now, I also doubt the restriction might come from my network. Thank you so much for your time!

**Comment by muzairkhattak** [comment]
No problem! I'm glad it worked. 

Kind regards!
